### ISSUE TITLE
compose up error on rpi 4B+

### ISSUE THREAD

**Issue by inglis-dl** [rickbassham/livestack#1]
docker-compose up results in the following error on raspberry pi 4B+ armv7l raspbian buster 10

Recreating livestack_livestack_1 ... done
Recreating livestack_nginx_1     ... done
Attaching to livestack_livestack_1, livestack_nginx_1
nginx_1      | standard_init_linux.go:219: exec user process caused: exec format error
livestack_nginx_1 exited with code 1
livestack_1  | Traceback (most recent call last):
livestack_1  |   File "main.py", line 17, in <module>
livestack_1  |     from livestack.stacking_service import Stacker
livestack_1  |   File "/app/livestack/stacking_service.py", line 19, in <module>
livestack_1  |     from colour_demosaicing import demosaicing_CFA_Bayer_bilinear
livestack_1  |   File "/usr/local/lib/python3.8/site-packages/colour_demosaicing/__init__.py", line 19, in <module>
livestack_1  |     import colour
livestack_1  |   File "/usr/local/lib/python3.8/site-packages/colour/__init__.py", line 97, in <module>
livestack_1  |     from .io import (LUT1D, LUT3x1D, LUT3D, LUTSequence, READ_IMAGE_METHODS,
livestack_1  |   File "/usr/local/lib/python3.8/site-packages/colour/io/__init__.py", line 7, in <module>
livestack_1  |     from .image import ImageAttribute_Specification, convert_bit_depth
livestack_1  |   File "/usr/local/lib/python3.8/site-packages/colour/io/image.py", line 99, in <module>
livestack_1  |     'float128', np.float128, None, 1, False)
livestack_1  |   File "/usr/local/lib/python3.8/site-packages/numpy/__init__.py", line 214, in __getattr__
livestack_1  |     raise AttributeError("module {!r} has no attribute "
livestack_1  | AttributeError: module 'numpy' has no attribute 'float128'
livestack_livestack_1 exited with code 1

**Comment by rickbassham** [comment]
Thanks. Looks like it is an issue in the colour-science package.

https://github.com/colour-science/colour/issues/663

They have created a fix for it, but it isn't released yet. I'm going to try a build off of there develop branch to see if it works.

**Comment by rickbassham** [comment]
Try using this branch and let me know if it loads.

`beta/fix_colour_demosaicing_rpi`

```
git checkout beta/fix_colour_demosaicing_rpi
```

**Comment by inglis-dl** [comment]
stellarmate@stellarmate:~/Documents/livestack $ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/beta/fix_colour_demosaicing_rpi
  remotes/origin/master
stellarmate@stellarmate:~/Documents/livestack $ git checkout fix_colour_demosaicing_rpi
error: pathspec 'fix_colour_demosaicing_rpi' did not match any file(s) known to git
stellarmate@stellarmate:~/Documents/livestack $ git checkout beta/fix_colour_demosaicing_rpi
Branch 'beta/fix_colour_demosaicing_rpi' set up to track remote branch 'beta/fix_colour_demosaicing_rpi' from 'origin'.
Switched to a new branch 'beta/fix_colour_demosaicing_rpi'
stellarmate@stellarmate:~/Documents/livestack $ diff ../docker-compose.yml docker-compose.yml 
8c8
<       - /home/stellarmate/Pictures:/livestack/input
---
>       - ./data/input:/livestack/input
stellarmate@stellarmate:~/Documents/livestack $ cp ../docker-compose.yml .
stellarmate@stellarmate:~/Documents/livestack $ docker-compose up --force-recreate
Recreating livestack_nginx_1     ... done
Recreating livestack_livestack_1 ... done
Attaching to livestack_livestack_1, livestack_nginx_1
nginx_1      | standard_init_linux.go:219: exec user process caused: exec format error
livestack_nginx_1 exited with code 1
livestack_1  | Traceback (most recent call last):
livestack_1  |   File "main.py", line 17, in <module>
livestack_1  |     from livestack.stacking_service import Stacker
livestack_1  |   File "/app/livestack/stacking_service.py", line 19, in <module>
livestack_1  |     from colour_demosaicing import demosaicing_CFA_Bayer_bilinear
livestack_1  |   File "/usr/local/lib/python3.8/site-packages/colour_demosaicing/__init__.py", line 19, in <module>
livestack_1  |     import colour
livestack_1  |   File "/usr/local/lib/python3.8/site-packages/colour/__init__.py", line 97, in <module>
livestack_1  |     from .io import (LUT1D, LUT3x1D, LUT3D, LUTSequence, READ_IMAGE_METHODS,
livestack_1  |   File "/usr/local/lib/python3.8/site-packages/colour/io/__init__.py", line 7, in <module>
livestack_1  |     from .image import ImageAttribute_Specification, convert_bit_depth
livestack_1  |   File "/usr/local/lib/python3.8/site-packages/colour/io/image.py", line 99, in <module>
livestack_1  |     'float128', np.float128, None, 1, False)
livestack_1  |   File "/usr/local/lib/python3.8/site-packages/numpy/__init__.py", line 214, in __getattr__
livestack_1  |     raise AttributeError("module {!r} has no attribute "
livestack_1  | AttributeError: module 'numpy' has no attribute 'float128'
livestack_livestack_1 exited with code 1

**Comment by inglis-dl** [comment]
sorry, not familiar with docker ... i will do a docker-compose build first then docker-compose up ...

**Comment by inglis-dl** [comment]
after build the up is either slow or hanging and nothing on localhost:3000/#/livestack

stellarmate@stellarmate:~/Documents/livestack $ docker-compose build
nginx uses an image, skipping
Building livestack
Step 1/8 : FROM rickbassham/python-astro:latest
 ---> e19a32458a5e
Step 2/8 : RUN mkdir /app
 ---> Using cache
 ---> e43bcc3f233f
Step 3/8 : WORKDIR /app
 ---> Using cache
 ---> da2655350e9c
Step 4/8 : COPY Pipfile /app
 ---> 3d7667cfe193
Step 5/8 : COPY Pipfile.lock /app
 ---> 4d72a66065bc
Step 6/8 : RUN pipenv install --system --deploy
 ---> Running in da8b692be2fd
Installing dependencies from Pipfile.lock (7d82ed)...
Removing intermediate container da8b692be2fd
 ---> 1fb5becaf78c
Step 7/8 : COPY . /app
 ---> d9298487f8f4
Step 8/8 : CMD [ "python", "main.py" ]
 ---> Running in daad94175146
Removing intermediate container daad94175146
 ---> 32365f220892

Successfully built 32365f220892
Successfully tagged rickbassham/livestack:latest
stellarmate@stellarmate:~/Documents/livestack $ docker-compose up                 
Starting livestack_nginx_1       ... done
Recreating livestack_livestack_1 ... done
Attaching to livestack_nginx_1, livestack_livestack_1
nginx_1      | standard_init_linux.go:219: exec user process caused: exec format error
livestack_nginx_1 exited with code 1
livestack_1  | INFO:root:start processing file /livestack/input/Bias/Bias_Bias_001.fits
livestack_1  | INFO:root:done processing file /livestack/input/Bias/Bias_Bias_001.fits in 1024.229ms
livestack_1  | ERROR:root:'Image' object has no attribute 'image_type'
livestack_1  | Exception in thread Thread-1:
livestack_1  | Traceback (most recent call last):
livestack_1  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
livestack_1  |     self.run()
livestack_1  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
livestack_1  |     self._target(*self._args, **self._kwargs)
livestack_1  |   File "/app/livestack/stacking_service.py", line 432, in _worker
livestack_1  |     self._process_item(item)
livestack_1  |   File "/app/livestack/stacking_service.py", line 288, in _process_item
livestack_1  |     if img.image_type == "LIGHT":
livestack_1  | AttributeError: 'Image' object has no attribute 'image_type'

**Comment by inglis-dl** [comment]
the problem may be that in Pictures there are Lights, Darks, Flats and Bias subdirs.  I had run siril to script process master calibration frames for reuse.  Some auxilliary files do not have a fits header element IMAGETYP or even the primary source fits files have a IMAGETYP not recognized by livestack

**Comment by rickbassham** [comment]
Yeah, I've only tested this with images produced by KStars with my ASI1600 cameras.

I just pushed up a new command to the image that will dump all the fits headers to a file you can send me, which should let me debug a little better.

```bash
git checkout beta/fix_colour_demosaicing_rpi
git pull
docker-compose build
docker-compose run livestack python main.py --analyze | gzip > headers.txt.gz
```

Then you can send me the `headers.txt.gz` file that is output. This will contain all the FITS headers from the files in your input folder, so if you have GPS data in there, you may want to send the file directly to me instead of posting it on the issue.

**Comment by inglis-dl** [comment]
Rick, see attached

- Dean

**Comment by inglis-dl** [comment]
see headers  attached ...

[headers.txt.gz](https://github.com/rickbassham/livestack/files/5754535/headers.txt.gz)

**Comment by rickbassham** [comment]
Ok, just pushed up a change to ignore bias files for now instead of failing. I shoot dark-flats instead of bias, so I'm not quite sure how to handle them at the moment.

```
git pull
docker-compose build
docker-compose up
```

**Comment by inglis-dl** [comment]
is there some residual code ? 

stellarmate@stellarmate:~/Documents/livestack $ docker-compose up   
Recreating livestack_livestack_1 ... done
Starting livestack_nginx_1       ... done
Attaching to livestack_nginx_1, livestack_livestack_1
nginx_1      | standard_init_linux.go:219: exec user process caused: exec format error
livestack_nginx_1 exited with code 1
livestack_1  | Traceback (most recent call last):
livestack_1  |   File "main.py", line 102, in <module>
livestack_1  |     if sys.argv[1] == "--analyze":
livestack_1  | IndexError: list index out of range
livestack_livestack_1 exited with code 1

**Comment by rickbassham** [comment]
One more try. Just pushed up another fix.

**Comment by inglis-dl** [comment]
I passed a dummy arg to get past that and realized as it was working through many flats / darks / lights I should reduce the load to something sensible to try it out: 10 darks, 10 flats, 10 bias and 5 lights .  I just tried the fix and it worked but now I realize since im not running ekos web, running stellarmate web manager which already uses localhost:3000/#/, so I get nothing in my browser at localhost:3000/#/livestack?

**Comment by rickbassham** [comment]
If you used `docker-compose up` you can browse to http://localhost:8080. Or just look in the output folder you configured for the live stack output.

**Comment by inglis-dl** [comment]
nice! I will post the result to the indilib form and maybe get some more info on how to run livestack and ekos-web ?

**Comment by rickbassham** [comment]
Awesome. Also, I created an "Issue Template" in the github repo to show results of a stack. I'd appreciate if you uploaded there as well.

**Comment by rickbassham** [comment]
Or better yet, use the github discussions to post a "Show and Tell" discussion with your output. I'd love to see how they turn out, good or bad.

**Comment by rickbassham** [comment]
@all-contributors please add @inglis-dl for bug and userTesting
